### ISSUE TITLE
fmadd.d	fa0, [1], [1], [0] produces 0 in fa0

### ISSUE THREAD

**Issue by FrBrGeorge** [TheThirdOne/JSoftFloat#6]
This code produces actual zero when computes 1*1+0 by fmadd.d fa0, ft1, ft2, ft0:
```
	li		t1 1
	fcvt.d.w	ft2, t1
	fcvt.d.w	ft1, t1
	fcvt.d.w	ft0, zero
	fmadd.d		fa0, ft2, ft1, ft0
```
The result is 0 in fa0 instead of 1

The problem is [here](https://github.com/TheThirdOne/JSoftFloat/blob/master/src/jsoftfloat/operations/Arithmetic.java#L146). Perhaps, [here](https://github.com/TheThirdOne/JSoftFloat/blob/master/src/jsoftfloat/operations/Arithmetic.java#L144) must be not `||`, but `&&`?

**Comment by TheThirdOne** [comment]
The `multiplication.isZero()` simply should never be true. Just removing the entire if statement would be an improvement, but working on this to get proper rounding will be harder. 

I think including some of the code from `add` would properly handle the rounding of zeros.
